name: Calorigram
options:
  bundleIdPrefix: com.calorigram
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: ru

targets:
  Calorigram:
    type: application
    platform: iOS
    sources:
      - path: Calorigram/App
      - path: Calorigram/Models
      - path: Calorigram/Services
      - path: Calorigram/ViewModels
      - path: Calorigram/Views
      - path: Calorigram/Utils
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.calorigram.app
      SWIFT_VERSION: "5.9"
      TARGETED_DEVICE_FAMILY: "1,2"
      INFOPLIST_FILE: Info.plist
      CODE_SIGN_ENTITLEMENTS: Calorigram/Calorigram.entitlements
      SWIFT_EMIT_LOC_STRINGS: YES
      SWIFT_OBJC_BRIDGING_HEADER: ""
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Calorigram
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UIRequiredDeviceCapabilities: [armv7]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSPhotoLibraryUsageDescription: "Приложению нужен доступ к фото для анализа блюд"
        NSCameraUsageDescription: "Приложению нужен доступ к камере для фотографирования блюд"
        NSPhotoLibraryAddUsageDescription: "Приложению нужен доступ для сохранения фотографий"
    dependencies: []
    settings:
      base:
        SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Automatic
        PROVISIONING_PROFILE_SPECIFIER: ""
    scheme:
      testTargets:
        - CalorigramTests

  CalorigramTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: CalorigramTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.calorigram.appTests
      SWIFT_VERSION: "5.9"
    dependencies:
      - target: Calorigram

schemes:
  Calorigram:
    build:
      targets:
        Calorigram: all
    test:
      targets:
        - CalorigramTests
    run:
      config: Debug

